apiVersion: v1
kind: Service
metadata:
  name: onlynode2
  annotations:
    # external-dns.alpha.kubernetes.io/hostname: bomk8stest.azure.cloud.bmw
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  ports:
    - port: 2181
      name: client
      protocol: TCP
  selector:
    "statefulset.kubernetes.io/pod-name": my-release-zookeeper-2
  type: ClusterIP