apiVersion: solr.bloomberg.com/v1beta1
kind: SolrCloud
metadata:
  name: example
spec:
  customSolrKubeOptions:
    podOptions:
      resources:
        requests:
          memory: 6G
  dataStorage:
    persistent:
      pvcTemplate:
        spec:
          resources:
            requests:
              storage: 20Gi
      reclaimPolicy: Delete
  replicas: 3
  solrGcTune: -XX:SurvivorRatio=4 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=8
  solrImage:
    tag: 8.7.0
  solrJavaMem: -Xms4g -Xmx4g
  solrOpts: -Dsolr.autoSoftCommit.maxTime=10000
  zookeeperRef:
    provided:
      replicas: 3