apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kafka-pubsub
  namespace: default
spec:
  type: pubsub.kafka
  version: v1
  metadata:
      # Kafka broker connection setting
    - name: brokers
      value: "dapr-kafka.default.svc.cluster.local:9092"
    - name: authRequired
      value: "false"
    - name: saslUsername
      value: "adminuser"
    - name: saslPassword
      value: "!CCCCCXXXX"
    - name: maxMessageBytes
      value: 1024